### ISSUE TITLE
openvpn server ip is?    

### ISSUE THREAD

**Issue by icetomato** [2stacks/docker-ovpn#8]
Hi,bro:
          I get some problem,  i don't konw  what is the openvpn server ip?
          it'is not 10.43.95.1

**Comment by 2stacks** [comment]
That depends on how/where you deploy it.  10.43.95.1 is the internal IP the
OpenVPN server uses when clients connect.  Clients should be assigned
something similar to that when they connect.  If you expose the Openvpn
container ports with

>     ports:
>       - "443:443"
>       - "1194:1194/udp"

Then the external IP of the Openvpn server is that of the Docker Host you ran the container on.  Hope that helps.

**Comment by icetomato** [comment]
First of all, I would like to talk about one of my requirements. For example, the server on my public network deployed a web service with a port of 8000. But I don't want everyone on the Internet to access it. Only the client in the VPN network can access it, that is, the internal address of OpenVPN server + port.

**Comment by 2stacks** [comment]
I would need more info regarding your setup.  Are you deploying the openvpn
container on the same host as the webserver?  Are you running the webserver
inside a container?  The answer to that will determine which IP the
webserver needs to allow access from.  The internal IPs that OpenVPN
assigns are nated to the IP assigned by the Docker bridge network.  Those
are in turn nated to the IP of the Docker Host when egressing the host.
This is a rather simplified answer.  Again I'd need more details to help.

If you really want to allow access from the private subnet assigned by
openvpn you'd have to modify the iptables that are built in to the
container.  Look at the bottom of this file to see where to change that.

https://github.com/2stacks/docker-ovpn/blob/master/bin/run

Let me know if you have any other questions.
